# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/redirect, roles: [ROLE_USER, ROLE_ADMIN] }
    - { path: ^/user/*, roles: ROLE_USER }
    - { path: ^/admin/*, roles: ROLE_ADMIN }
    encoders:
        BackendBundle\Entity\User:
            algorithm: bcrypt
            cost: 13
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db_provider:
            entity:
                class: BackendBundle:Usuario
                property: user


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout_on_user_change: true
            provider: user_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
