admin_index:
  path: /
  defaults: {_controller: AppBundle:Admin:index}

admin_project:
  path: /project
  defaults: {_controller: AppBundle:Admin:project}

admin_project_create:
  path: /project/create
  defaults: {_controller: AppBundle:Admin:projectCreate}

admin_business_create:
  path: /business/create
  defaults: {_controller: AppBundle:Admin:businessCreate}