admin_index:
  path: /
  defaults: {_controller: AppBundle:admin:index}

# Project #
admin_project:
  path: /project
  defaults: {_controller: AppBundle:admin:project}

admin_project_create:
  path: /project/create
  defaults: {_controller: AppBundle:admin:projectCreate}

admin_project_edit:
  path: /project/edit/{id}
  defaults: {_controller: AppBundle:admin:projectEdit}

admin_project_delete:
  path: /project/delete/{id}
  defaults: {_controller: AppBundle:admin:projectDelete}
# Project #

# Business #
admin_business:
  path: /business
  defaults: {_controller: AppBundle:admin:business}

admin_business_create:
  path: /business/create
  defaults: {_controller: AppBundle:admin:businessCreate}

admin_business_edit:
  path: /business/edit/{id}
  defaults: {_controller: AppBundle:admin:businessEdit}

admin_business_delete:
  path: /business/delete/{id}
  defaults: {_controller: AppBundle:admin:businessDelete}
# Business #