redirect:
  path: /redirect
  defaults: {_controller: AppBundle:Security:redirect}

login:
  path: /login
  defaults: {_controller: AppBundle:Security:login}

login_check:
  path: /login_check

logout:
  path: /logout
