-- MySQL Script generated by MySQL Workbench
-- Sun Nov 25 11:01:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sias` DEFAULT CHARACTER SET utf8 ;
USE `sias` ;

-- -----------------------------------------------------
-- Table `sias`.`Puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sias`.`Puesto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sias`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sias`.`Persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellidoP` VARCHAR(255) NOT NULL,
  `apellidoM` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sias`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sias`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona` INT NOT NULL,
  `user` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_Persona1_idx` (`persona` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`persona`)
    REFERENCES `sias`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sias`.`Desarrollador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sias`.`Desarrollador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `puesto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Desarrollador_Puesto_idx` (`puesto` ASC) VISIBLE,
  INDEX `fk_Desarrollador_Usuario1_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Desarrollador_Puesto`
    FOREIGN KEY (`puesto`)
    REFERENCES `sias`.`Puesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Desarrollador_Usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `sias`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sias`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sias`.`Empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sias`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sias`.`Proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `empresa` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Proyecto_Empresa1_idx` (`empresa` ASC) VISIBLE,
  CONSTRAINT `fk_Proyecto_Empresa1`
    FOREIGN KEY (`empresa`)
    REFERENCES `sias`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sias`.`Participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sias`.`Participante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desarrollador` INT NOT NULL,
  `proyecto` INT NOT NULL,
  `lider` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Participante_Desarrollador1_idx` (`desarrollador` ASC) VISIBLE,
  INDEX `fk_Participante_Proyecto1_idx` (`proyecto` ASC) VISIBLE,
  INDEX `fk_Participante_Participante1_idx` (`lider` ASC) VISIBLE,
  CONSTRAINT `fk_Participante_Desarrollador1`
    FOREIGN KEY (`desarrollador`)
    REFERENCES `sias`.`Desarrollador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participante_Proyecto1`
    FOREIGN KEY (`proyecto`)
    REFERENCES `sias`.`Proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participante_Participante1`
    FOREIGN KEY (`lider`)
    REFERENCES `sias`.`Participante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sias`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sias`.`Actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `fecha_inicio_real` DATETIME NULL,
  `fecha_fin_real` DATETIME NULL,
  `proyecto` INT NOT NULL,
  `participante` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Actividad_Proyecto1_idx` (`proyecto` ASC) VISIBLE,
  INDEX `fk_Actividad_Participante1_idx` (`participante` ASC) VISIBLE,
  CONSTRAINT `fk_Actividad_Proyecto1`
    FOREIGN KEY (`proyecto`)
    REFERENCES `sias`.`Proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Participante1`
    FOREIGN KEY (`participante`)
    REFERENCES `sias`.`Participante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
