app_index:
    path: /
    defaults: { _controller: AppBundle:Default:index }

_admin:
    resource: '@AppBundle/Resources/config/routing/admin.yml'
    prefix:   /admin
    
_user:
    resource: '@AppBundle/Resources/config/routing/user.yml'
    prefix:   /user

_session:
    resource: '@AppBundle/Resources/config/routing/session.yml'
    prefix:   /
    